import Link from "next/link";
import { CodeBlock, Footer, Header } from "../components";
import "./onboarding.css";

type Locale = "en" | "fr";
const topics = {
  en: [["Get started", "#start"], ["Architecture", "#architecture"], ["AML View", "#aml-view"], ["Internationalization", "#i18n"], ["Legacy migration", "#migration"], ["CLI reference", "#cli"], ["SEO toolkit", "#seo"], ["HTTP & MVC", "#http"], ["Views & assets", "#views"], ["Environment", "#environment"], ["Database", "#database"], ["Security", "#security"], ["Tests & production", "#production"], ["Build & deploy", "#deployment"], ["Troubleshooting", "#troubleshooting"]],
  fr: [["Bien démarrer", "#start"], ["Architecture", "#architecture"], ["AML View", "#aml-view"], ["Internationalisation", "#i18n"], ["Migration des anciens projets", "#migration"], ["Référence CLI", "#cli"], ["Outils SEO", "#seo"], ["HTTP et MVC", "#http"], ["Vues et fichiers", "#views"], ["Environnement", "#environment"], ["Base de données", "#database"], ["Sécurité", "#security"], ["Tests et production", "#production"], ["Build et déploiement", "#deployment"], ["Dépannage", "#troubleshooting"]],
};
const commands = {
  en: [["aml create .", "Create in the current folder"], ["aml create my-project", "Create a classic app folder"], ["aml create-view-app my-ui", "Create an AML View application"], ["aml install", "Install engine and dependencies"], ["aml serve", "Start from port 8910 with live reload"], ["aml routes", "List registered routes"], ["aml test", "Run tests/run.php"], ["aml build", "Create a verified production archive"], ["aml deploy production --dry-run", "Preview the exact remote changes"], ["aml deploy:status production", "Compare local and production manifests"], ["aml deploy production", "Deploy only added and modified files"], ["aml deploy:history production", "Show the private local deployment history"], ["aml deploy:rollback production", "Restore the previous release"], ["aml make:controller User", "Generate a controller"], ["aml make:model User", "Generate a model"], ["aml make:middleware Auth", "Generate middleware"], ["aml make:migration create_users_table", "Generate a migration"], ["aml env:init", "Create .env from .env.example"], ["aml env:list", "List variables and mask secrets"], ["aml env:get APP_DEBUG", "Read one variable"], ["aml env:set APP_DEBUG false", "Create or update one variable"], ["aml db:show", "Show database configuration"], ["aml doctor", "Check AML and the project"], ["aml cache:clear", "Clear application cache"], ["aml update --check", "Check for a new release"], ["aml update", "Install the latest release"], ["aml language fr", "Change the CLI language"]],
  fr: [["aml create .", "Créer dans le dossier courant"], ["aml create mon-projet", "Créer une application classique"], ["aml create-view-app mon-ui", "Créer une application AML View"], ["aml install", "Installer moteur et dépendances"], ["aml serve", "Démarrer à partir du port 8910 avec actualisation"], ["aml routes", "Afficher les routes"], ["aml test", "Exécuter tests/run.php"], ["aml build", "Créer une archive de production vérifiée"], ["aml deploy production --dry-run", "Prévisualiser précisément les changements distants"], ["aml deploy:status production", "Comparer les manifestes local et distant"], ["aml deploy production", "Déployer uniquement les fichiers utiles"], ["aml deploy:history production", "Afficher l’historique local privé"], ["aml deploy:rollback production", "Restaurer la version précédente"], ["aml make:controller User", "Générer un contrôleur"], ["aml make:model User", "Générer un modèle"], ["aml make:middleware Auth", "Générer un middleware"], ["aml make:migration create_users_table", "Générer une migration"], ["aml env:init", "Créer .env depuis .env.example"], ["aml env:list", "Lister les variables et masquer secrets"], ["aml env:get APP_DEBUG", "Lire une variable"], ["aml env:set APP_DEBUG false", "Créer ou modifier une variable"], ["aml db:show", "Afficher la configuration de la base"], ["aml doctor", "Vérifier AML et le projet"], ["aml cache:clear", "Vider le cache"], ["aml update --check", "Chercher une nouvelle version"], ["aml update", "Installer la dernière version"], ["aml language en", "Changer la langue du CLI"]],
};

const commandRows = {
  en: [...commands.en.slice(0, 3), ["aml create-api my-api", "Create a focused JSON API"], ...commands.en.slice(3)],
  fr: [...commands.fr.slice(0, 3), ["aml create-api mon-api", "Créer une API JSON ciblée"], ...commands.fr.slice(3)],
};

function AmlViewDocsSections({ locale }: { locale: Locale }) {
  const fr = locale === "fr";
  return <>
    <section id="aml-view">
      <span className="doc-label">13 — AML View</span>
      <h2>{fr ? "Construire une interface déclarative et réactive" : "Build a declarative, reactive interface"}</h2>
      <p>{fr ? "AML View est la couche frontend optionnelle de PHPAML. PHP rend le premier document, puis Engine gère localement l’état, les effets, les collections, les thèmes et la navigation." : "AML View is PHPAML’s optional frontend layer. PHP renders the first document, then Engine manages state, effects, collections, themes, and navigation locally."}</p>
      <CodeBlock>{`aml create-view-app ${fr ? "mon-interface" : "my-interface"}\ncd ${fr ? "mon-interface" : "my-interface"}\naml serve\n# http://127.0.0.1:8910`}</CodeBlock>
      <div className="file-tree"><pre>{`src/\n├── controllers/\n├── models/\n├── middleware/\n└── views/\n    ├── pages/{route}/page.php\n    ├── components/\n    ├── layouts/\n    ├── states/{Loading,Error,NotFound}.php\n    ├── stylesheets/\n    ├── themes/\n    └── assets/`}</pre></div>
      <p>{fr ? "src/views, src/controllers et src/models sont obligatoires. Les CSS sont collectés depuis src/views/stylesheets. Les ressources importées restent dans assets ; favicon, robots.txt et sitemap.xml restent dans public/." : "src/views, src/controllers, and src/models are required. CSS is collected from src/views/stylesheets. Imported assets stay in assets; favicon, robots.txt, and sitemap.xml stay in public/."}</p>
      <CodeBlock>{`#[State]\npublic int $count = 0;\n\npublic function body(): View\n{\n    return VStack(\n        Heading('AML View')->class('page-title'),\n        Text("Count: {$this->count}"),\n        Button('Add one')->onClick(fn () => $this->count++),\n    );\n}`}</CodeBlock>
      <p>{fr ? "Les interactions compilées s’exécutent dans le navigateur sans rappeler PHP. Les effets offrent dépendances, nettoyage, debounce, throttle, annulation latest, états loading/success/error et protection contre les cycles." : "Compiled interactions run in the browser without calling PHP again. Effects provide dependencies, cleanup, debounce, throttle, latest cancellation, loading/success/error states, and cycle protection."}</p>
      <div className="notice"><strong>{fr ? "Navigation sans rechargement" : "Navigation without reload"}</strong><p>{fr ? "Engine remplace uniquement la zone RouterView, conserve le document, met à jour l’historique, les métadonnées et le focus, puis utilise Loading, Error ou NotFound selon la réponse." : "Engine replaces only the RouterView boundary, preserves the document, updates history, metadata, and focus, then uses Loading, Error, or NotFound for the response state."}</p></div>
    </section>
    <section id="i18n">
      <span className="doc-label">14 — i18n</span>
      <h2>{fr ? "Internationalisation JSON" : "JSON internationalization"}</h2>
      <CodeBlock>{`aml install i18n\naml i18n:add es\naml i18n:list\naml i18n:check\naml i18n:missing fr\naml i18n:set-default en`}</CodeBlock>
      <p>{fr ? "Organisez librement les fichiers sous src/locales/{langue}. Le chemin devient une clé pointée, les paramètres utilisent :nom, les pluriels one/other utilisent le nombre et LocaleResolver choisit une langue supportée depuis la route, le cookie ou Accept-Language." : "Organize files freely under src/locales/{locale}. Paths become dotted keys, parameters use :name, one/other plural forms use the count, and LocaleResolver selects a supported locale from the route, cookie, or Accept-Language."}</p>
    </section>
  </>;
}

function ArchitectureSection({ locale }: { locale: Locale }) {
  const fr = locale === "fr";
  return <section id="architecture">
    <span className="doc-label">02 — Concepts</span>
    <h2>{fr ? "Trois structures lisibles, une même configuration" : "Three readable structures, one configuration model"}</h2>
    <p>{fr ? "PHPAML sépare les responsabilités sans imposer de dossiers inutiles. Le projet classique conserve app et sa carte de routes WebApp. AML View organise le backend et l’interface sous src. Une API retire les vues et adopte une classe de route par ressource." : "PHPAML separates responsibilities without adding empty folders. The classic project keeps app and its WebApp route map. AML View organizes backend and interface code under src. An API removes views and uses one route class per resource."}</p>
    <div className="architecture-variants">
      <div><small>{fr ? "APPLICATION CLASSIQUE" : "CLASSIC APPLICATION"}</small><div className="file-tree"><pre>{`app/
├── Controllers/
├── Models/
└── views/
routes/WebApp.php
public/index.php`}</pre></div></div>
      <div><small>AML VIEW</small><div className="file-tree"><pre>{`src/
├── controllers/
├── models/
├── middleware/
├── locales/
└── views/
    ├── pages/
    ├── components/
    ├── layouts/
    ├── states/
    └── stylesheets/
routes/WebApp.php`}</pre></div></div>
      <div><small>API</small><div className="file-tree"><pre>{`src/
├── controllers/
├── models/
├── repositories/
├── requests/
├── resources/
├── middleware/
└── routes/
    └── MovieRoute.php
public/index.php`}</pre></div></div>
    </div>
    <h3>{fr ? "Configuration sans dossier configs" : "Configuration without a configs folder"}</h3>
    <p>{fr ? "Dans les nouveaux projets, phpaml.json contient les choix partageables et .env les secrets ou valeurs propres à la machine. PHPAML construit runtime/config/app.php automatiquement. Ce dernier appartient au moteur et ne doit jamais être édité." : "In new projects, phpaml.json stores shareable choices while .env stores secrets and machine-specific values. PHPAML builds runtime/config/app.php automatically. That generated file belongs to the runtime and must never be edited."}</p>
    <h3>{fr ? "Cycle d’une requête" : "Request lifecycle"}</h3>
    <ol className="doc-steps"><li><b>public/index.php</b> {fr ? "charge phpaml.json et .env." : "loads phpaml.json and .env."}</li><li>{fr ? "Les middlewares traitent la requête." : "Middleware processes the request."}</li><li>{fr ? "Le routeur découvre routes/ ou src/routes/." : "The router discovers routes/ or src/routes/."}</li><li>{fr ? "Le conteneur injecte les dépendances du contrôleur." : "The container injects controller dependencies."}</li><li>{fr ? "L’action retourne HTML, JSON ou une redirection." : "The action returns HTML, JSON, or a redirect."}</li></ol>
  </section>;
}

function PackageInstallSection({ locale }: { locale: Locale }) {
  const fr = locale === "fr";
  return <section id="packages">
    <span className="doc-label">02.2 — PACKAGIST</span>
    <h2>{fr ? "Installer les composants indépendamment" : "Install components independently"}</h2>
    <p>{fr ? "Les commandes de création AML configurent automatiquement les bons composants. Dans un projet Composer existant, déclarez ensemble les paquets en préversion qui collaborent afin que le projet racine autorise explicitement leur niveau de stabilité." : "AML creation commands configure the correct components automatically. In an existing Composer project, declare collaborating prerelease packages together so the root project explicitly accepts their stability level."}</p>
    <div className="command-pair"><div><small>AML VIEW + ENGINE</small><CodeBlock>{`composer require \\
  phpaml/view:^0.1@beta \\
  phpaml/engine:^0.1@beta`}</CodeBlock></div><div><small>DATA + MONGODB</small><CodeBlock>{`composer require \\
  phpaml/data:^0.2@alpha \\
  phpaml/data-mongodb:^0.1@alpha`}</CodeBlock></div></div>
    <p>{fr ? "Engine, Data et i18n peuvent aussi être installés seuls. L’adaptateur MongoDB nécessite l’extension PHP mongodb, tandis que Data SQL nécessite PDO." : "Engine, Data, and i18n can also be installed alone. The MongoDB adapter requires the PHP mongodb extension, while SQL Data requires PDO."}</p>
  </section>;
}

export function DocsPage({ locale }: { locale: Locale }) {
  const fr = locale === "fr", prefix = fr ? "/fr" : "";
  const tx = fr ? { label:"Documentation officielle", title:"Construire avec PHPAML.", accent:"Du premier projet à la production.", lead:"Guide complet de l’environnement autonome AML et du mini-framework MVC PHPAML.", nav:"Dans ce guide" } : { label:"Official documentation", title:"Build with PHPAML.", accent:"From first project to production.", lead:"Complete guide to the autonomous AML environment and the PHPAML MVC mini-framework.", nav:"In this guide" };
  return <><Header locale={locale} path="/docs" /><main>
    <section className="page-hero shell"><p className="eyebrow"><span /> {tx.label}</p><h1>{tx.title}<br /><em>{tx.accent}</em></h1><p>{tx.lead}</p><div className="doc-stats"><span><strong>13</strong>{fr?" chapitres":" chapters"}</span><span><strong>30+</strong>{fr?" commandes":" commands"}</span><span><strong>EN / FR</strong>{fr?" référence bilingue":" bilingual reference"}</span></div></section>
    <section className="docs-layout shell"><aside><strong>{tx.nav}</strong>{topics[locale].map(([n,h])=><a key={h} href={h}>{n}</a>)}</aside><div className="docs-content">
      <section id="start"><span className="doc-label">01 — {fr?"Démarrage":"Getting started"}</span><h2>{fr?"Trois parcours, un premier résultat en moins de cinq minutes":"Three paths, a first result in under five minutes"}</h2><p>{fr?"AML inclut PHP et Composer, crée la structure choisie et installe automatiquement ses dépendances. Choisissez l’application classique pour MVC, AML View pour une interface déclarative réactive, ou API pour un service JSON ciblé.":"AML bundles PHP and Composer, creates the selected structure, and installs its dependencies automatically. Choose the classic application for MVC, AML View for a declarative reactive interface, or API for a focused JSON service."}</p><div className="onboarding-grid"><div><small>01 · {fr?"APPLICATION CLASSIQUE":"CLASSIC APPLICATION"}</small><CodeBlock>{`aml create ${fr?"mon-projet":"my-project"}\ncd ${fr?"mon-projet":"my-project"}\naml serve`}</CodeBlock></div><div><small>02 · AML VIEW</small><CodeBlock>{`aml create-view-app ${fr?"mon-interface":"my-interface"}\ncd ${fr?"mon-interface":"my-interface"}\naml serve`}</CodeBlock></div><div><small>03 · API</small><CodeBlock>{`aml create-api ${fr?"mon-api":"my-api"}\ncd ${fr?"mon-api":"my-api"}\naml serve`}</CodeBlock></div></div><p>{fr?"Ouvrez ensuite":"Then open"} <code>http://127.0.0.1:8910</code>. {fr?"Utilisez aml doctor si vous souhaitez vérifier l’environnement. Pour le dossier actuel, utilisez":"Use aml doctor whenever you want to verify the environment. For the current folder, use"} <code>aml create .</code>.</p><div className="notice"><strong>{fr?"Installation automatique et actualisation":"Automatic installation and live reload"}</strong><p>{fr?"Les commandes de création préparent directement un projet exécutable. Le navigateur se recharge ensuite après chaque modification prise en charge.":"Creation commands produce a runnable project directly. The browser then reloads after each supported change."}</p></div></section>
      <ArchitectureSection locale={locale} />
      <section id="migration"><span className="doc-label">02.1 — {fr?"Migration":"Migration"}</span><h2>{fr?"Passer de aml_env à runtime":"Move from aml_env to runtime"}</h2><p>{fr?"Les projets plus anciens utilisent aml_env, info.json ou app/View. La migration renomme aussi app/View en app/UI. Prévisualisez toujours la conversion avant de l’appliquer. AML crée une sauvegarde dans runtime/storage/migrations avant de renommer les éléments et d’actualiser les références connues.":"Older projects use aml_env, info.json, or app/View. The migration also renames app/View to app/UI. Always preview the conversion before applying it. AML creates a backup under runtime/storage/migrations before renaming files and updating known references."}</p><CodeBlock>{`aml migrate:structure\naml migrate:structure --apply --yes\naml doctor --offline\naml test`}</CodeBlock><div className="notice"><strong>{fr?"Sauvegarde automatique":"Automatic backup"}</strong><p><code>runtime/storage/migrations/structure-&lt;date&gt;/</code></p></div></section>
      <section id="cli"><span className="doc-label">03 — CLI</span><h2>{fr?"Référence des commandes AML":"AML command reference"}</h2><p>{fr?"Au premier lancement, AML demande English ou Français. Les sorties, diagnostics et erreurs suivent ce choix. AML_LANG=en ou AML_LANG=fr remplace temporairement la langue.":"On first launch, AML asks for English or French. Output, diagnostics, and errors follow that choice. AML_LANG=en or AML_LANG=fr temporarily overrides it."}</p><div className="command-reference">{commandRows[locale].map(([c,d])=><div key={c}><code>{c}</code><span>{d}</span></div>)}</div><h3>{fr?"Options utiles":"Useful options"}</h3><CodeBlock>{`aml create ${fr?"projet":"project"} --version 0.1.0\naml create ${fr?"projet":"project"} --offline\naml install --production\naml install --refresh\naml doctor --offline\naml doctor --port 8080\naml doctor --production --json\naml update --version 1.3.0`}</CodeBlock></section>
      <section id="http"><span className="doc-label">04 — HTTP & MVC</span><h2>{fr?"Routes, requêtes et contrôleurs":"Routes, requests, and controllers"}</h2><CodeBlock>{`'GET /users/{id}' => [\n    'handler' => [UserController::class, 'show'],\n    'middleware' => [AuthMiddleware::class],\n    'name' => 'users.show',\n],`}</CodeBlock><CodeBlock>{`public function show(Request $request): Response\n{\n    return $this->json(['id' => $request->attribute('id')]);\n}`}</CodeBlock><p>{fr?"Request fournit method(), path(), query(), input(), cookie(), header(), server() et attribute(). Le JSON est décodé automatiquement. Une route inconnue retourne 404 ; une mauvaise méthode retourne 405.":"Request provides method(), path(), query(), input(), cookie(), header(), server(), and attribute(). JSON is decoded automatically. An unknown route returns 404; an unsupported method returns 405."}</p><CodeBlock>{`return Response::html('<h1>Hello</h1>');\nreturn Response::json(['ok' => true], 201);\nreturn Response::redirect('/login');\nreturn $this->view('users/show.php', ['user' => $user]);`}</CodeBlock></section>
      <section id="views"><span className="doc-label">05 — UI</span><h2>{fr?"Vues déclaratives et ressources":"Declarative views and assets"}</h2><p>{fr?"Les applications classiques peuvent conserver leurs templates PHP et partials. Une application AML View place ses pages, composants, layouts et états dans src/views. Les feuilles de style sont découvertes automatiquement dans src/views/stylesheets, tandis que le moteur JavaScript est servi automatiquement par AML.":"Classic applications may keep PHP templates and partials. An AML View application places pages, components, layouts, and states in src/views. Stylesheets are discovered automatically under src/views/stylesheets, while AML serves the JavaScript engine automatically."}</p><CodeBlock>{`src/views/pages/home/page.php\nsrc/views/components/Navigation.php\nsrc/views/layouts/DashboardLayout.php\nsrc/views/stylesheets/pages/home.css\nassets/images/hero.webp\npublic/favicon.svg`}</CodeBlock></section>
      <section id="environment"><span className="doc-label">06 — ENV</span><h2>{fr?"Configurer .env en ligne de commande":"Configure .env from the command line"}</h2><CodeBlock>{`aml env:init\naml env:set APP_DEBUG false\naml env:get APP_DEBUG\naml env:list`}</CodeBlock><p>{fr?"env:init copie .env.example ; --force remplace un fichier existant. env:list masque mots de passe, secrets, clés et jetons. Ne publiez jamais .env dans Git.":"env:init copies .env.example; --force replaces an existing file. env:list masks passwords, secrets, keys, and tokens. Never commit .env to Git."}</p></section>
      <section id="database"><span className="doc-label">07 — Data</span><h2>{fr?"SQLite, MySQL et migrations":"SQLite, MySQL, and migrations"}</h2><p>{fr?"SQLite est la base locale par défaut. AML crée runtime/storage/database.sqlite et enregistre root/root par convention ; SQLite n’utilise pas réellement ces identifiants.":"SQLite is the default local database. AML creates runtime/storage/database.sqlite and records root/root by convention; SQLite does not actually use these credentials."}</p><CodeBlock>{`aml db:configure sqlite\naml db:configure sqlite --path storage/app.sqlite\naml db:show\n\naml db:configure mysql --host 127.0.0.1 --port 3306 \\\n  --database phpaml --user root --password root`}</CodeBlock><h3>{fr?"Migrations transactionnelles":"Transactional migrations"}</h3><CodeBlock>{`aml make:migration create_users_table\naml migrate
aml migrate:rollback --steps 1`}</CodeBlock><p>{fr?"Les migrations sont enregistrées dans aml_migrations. Les migrations sont ordonnées et verrouillées. migrate:rollback exécute down() en ordre inverse. Le QueryBuilder fournit all() et insert() ; utilisez PDO préparé pour le reste.":"Migrations are recorded in aml_migrations. Migrations are ordered and locked. migrate:rollback runs down() in reverse order. QueryBuilder provides all() and insert(); use prepared PDO for everything else."}</p></section>
      <section id="security"><span className="doc-label">08 — Security</span><h2>{fr?"Validation, CSRF et middleware":"Validation, CSRF, and middleware"}</h2><CodeBlock>{`$valid = $validator->validate($request->input(), [\n  'email' => ['required', 'email'],\n  'name' => ['required', 'string', 'min:2', 'max:100'],\n]);`}</CodeBlock><p>{fr?"Règles : required, email, string, min:n et max:n. Protégez les routes d’écriture avec CsrfMiddleware et ajoutez <?= $this->csrfField() ?> aux formulaires. Pour une API, utilisez X-CSRF-Token.":"Rules: required, email, string, min:n, and max:n. Protect write routes with CsrfMiddleware and add <?= $this->csrfField() ?> to forms. For an API, use X-CSRF-Token."}</p><p>{fr?"SecurityHeadersMiddleware ajoute les en-têtes de sécurité ; les détails d’erreur sont masqués avec APP_DEBUG=false.":"SecurityHeadersMiddleware adds security headers; error details are hidden when APP_DEBUG=false."}</p></section>
      <section id="production"><span className="doc-label">09 — Shipping</span><h2>{fr?"Tester et préparer la production":"Test and prepare for production"}</h2><CodeBlock>{`aml test\naml install --production\naml doctor --production --json\naml routes`}</CodeBlock><p>{fr?"aml test utilise le PHP privé d’AML et exécute tests/run.php. --production exclut les dépendances de développement et optimise l’autoloader.":"aml test uses AML's private PHP and runs tests/run.php. --production excludes development dependencies and optimizes the autoloader."}</p><div className="notice"><strong>{fr?"Important":"Important"}</strong><p>{fr?"aml serve est réservé au développement. En production : serveur HTTP compatible PHP, HTTPS, APP_DEBUG=false, permissions minimales, sauvegardes et authentification adaptée.":"aml serve is for development only. In production: a PHP-compatible HTTP server, HTTPS, APP_DEBUG=false, minimal permissions, backups, and appropriate authentication."}</p></div></section>
      <section id="troubleshooting"><span className="doc-label">10 — Support</span><h2>{fr?"Résoudre les problèmes fréquents":"Solve common problems"}</h2><div className="faq"><details open><summary>{fr?"La commande aml est introuvable":"The aml command is not found"}</summary><p>{fr?"Ouvrez un nouveau terminal et vérifiez PATH : %LOCALAPPDATA%\\Programs\\PHPAML\\bin sous Windows, /usr/local/bin sous macOS/Linux.":"Open a new terminal and check PATH: %LOCALAPPDATA%\\Programs\\PHPAML\\bin on Windows, /usr/local/bin on macOS/Linux."}</p></details><details><summary>{fr?"L’environnement AML est absent":"The AML environment is missing"}</summary><p>{fr?"Depuis la racine du projet, lancez aml install.":"From the project root, run aml install."}</p></details><details><summary>{fr?"CSS ou JavaScript ne se charge pas":"CSS or JavaScript does not load"}</summary><p>{fr?"Vérifiez /public/, les majuscules du fichier et lancez aml serve depuis le dossier contenant public/index.php.":"Check /public/, filename casing, and run aml serve from the folder containing public/index.php."}</p></details><details><summary>{fr?"Le port 8000 est occupé":"Port 8000 is busy"}</summary><p><code>aml doctor --port 8080</code><br/><code>aml serve 127.0.0.1:8080</code></p></details><details><summary>{fr?"GitHub est inaccessible":"GitHub is unavailable"}</summary><p>{fr?"Utilisez aml create projet --offline ou aml install --offline pour réutiliser le cache.":"Use aml create project --offline or aml install --offline to reuse the cache."}</p></details></div></section>
      <section id="seo"><span className="doc-label">11 — SEO</span><h2>{fr?"Piloter le SEO depuis AML":"Control SEO from AML"}</h2><p>{fr?"AML centralise les métadonnées, génère les fichiers destinés aux moteurs de recherche et audite le HTML publié.":"AML centralizes metadata, generates search-engine files, and audits the published HTML."}</p><CodeBlock>{`aml seo:init\naml seo:set base_url "https://example.com"\naml seo:set title "My website"\naml seo:set description "A clear description between 50 and 160 characters."\naml seo:disallow /admin\naml seo:allow /admin/public\naml seo:generate\naml seo:audit https://example.com --json`}</CodeBlock><p>{fr?"seo:generate crée public/sitemap.xml et public/robots.txt depuis les routes GET statiques. Les routes interdites sont retirées du sitemap. seo:audit vérifie le titre, la description, l’URL canonique, Open Graph, Twitter Cards, JSON-LD, la langue, le viewport, le H1, les images et HTTPS.":"seo:generate creates public/sitemap.xml and public/robots.txt from static GET routes. Disallowed routes are removed from the sitemap. seo:audit checks the title, description, canonical URL, Open Graph, Twitter Cards, JSON-LD, language, viewport, H1, images, and HTTPS."}</p><div className="notice"><strong>{fr?"Indexation et sécurité":"Indexing and security"}</strong><p>{fr?"Une règle disallow guide les robots, mais ne protège pas une page. Utilisez l’authentification et les middlewares pour les zones privées.":"A disallow rule guides crawlers but does not protect a page. Use authentication and middleware for private areas."}</p></div></section>
      <section id="deployment">
        <span className="doc-label">12 — Deploy</span>
        <h2>{fr?"Construire et déployer partout":"Build and deploy anywhere"}</h2>
        <p>{fr?"aml build exécute les tests, vérifie public/.htaccess et crée une archive ZIP, un manifeste et un checksum SHA-256 dans output/. Les secrets et éléments non exécutables sont exclus : .env, journaux, bases SQLite, tests, fichiers temporaires, output/ et deliverables/.":"aml build runs the tests, checks public/.htaccess, and creates a ZIP archive, manifest, and SHA-256 checksum in output/. Secrets and non-runtime material are excluded: .env, logs, SQLite databases, tests, temporary files, output/, and deliverables/."}</p>
        <CodeBlock>{`aml build\naml build --skip-tests\n\naml deploy:configure production --host example.com --user deploy \\\n  --path /home/deploy/site --port 22 --key ~/.ssh/id_ed25519\naml deploy:check production\naml deploy production --dry-run\naml deploy:status production\naml deploy production\naml deploy:history production\naml deploy:rollback production\naml deploy:prune production --keep 5`}</CodeBlock>
        <p>{fr?"Après le premier envoi, AML compare les empreintes SHA-256 et ne transfère que les fichiers ajoutés ou modifiés. Il retire les fichiers supprimés, affiche le volume transféré, l’économie obtenue et la progression jusqu’à l’activation. --dry-run et deploy:status restent strictement en lecture seule.":"After the first upload, AML compares SHA-256 fingerprints and transfers only added or modified files. It removes deleted files and reports transferred size, savings, and progress through activation. --dry-run and deploy:status remain strictly read-only."}</p>
        <CodeBlock>{`[ 25%] Comparison completed\n+ public/version.txt\n~ src/controllers/HomeController.php\n- public/obsolete.txt\nTransfer: 42.3 KB of 8.40 MB — 99.5% saved\n[100%] Deployment completed`}</CodeBlock>
        <h3>{fr?"Choisir une stratégie":"Choose a strategy"}</h3>
        <div className="command-list"><div><code>releases</code><span>{fr?"Versions horodatées, lien current et retour arrière atomique":"Timestamped releases, current symlink, and atomic rollback"}</span></div><div><code>public-html</code><span>{fr?"Hébergement mutualisé avec public_html séparé":"Shared hosting with a separate public_html"}</span></div><div><code>sftp-only</code><span>{fr?"Serveur sans accès shell SSH":"Server without SSH shell access"}</span></div></div>
        <CodeBlock>{`aml deploy:configure hostinger --host example.com --user deploy \\\n  --path /home/user/domains/example.com \\\n  --strategy public-html \\\n  --public-path /home/user/domains/example.com/public_html \\\n  --key ~/.ssh/id_ed25519`}</CodeBlock>
        <p>{fr?"Le profil privé est conservé dans ~/.phpaml/deploy.json et l’historique dans ~/.phpaml/deploy-history.json, tous deux avec des permissions 600. L’historique conserve au plus 100 résultats sans hôte, chemin, utilisateur ni secret.":"The private profile is stored in ~/.phpaml/deploy.json and history in ~/.phpaml/deploy-history.json, both with 600 permissions. History retains up to 100 results without storing the host, path, user, or secrets."}</p>
        <div className="notice"><strong>{fr?"Déploiement protégé":"Protected deployment"}</strong><p>{fr?"AML vérifie les checksums, refuse les chemins d’archive dangereux, écrit l’historique atomiquement et arrête l’aperçu si le manifeste distant est inaccessible.":"AML verifies checksums, rejects unsafe archive paths, writes history atomically, and stops previews when the remote manifest cannot be reached."}</p></div>
      </section>
      <div className="docs-next"><span>{fr?"Prêt à construire votre première application ?":"Ready to build your first application?"}</span><div className="docs-next-links"><Link href={`${prefix}/news/first-aml-view-app-in-five-minutes`}>{fr?"Suivre le guide AML View":"Follow the AML View guide"} →</Link><Link href={`${prefix}/download`}>{fr?"Installer AML":"Install AML"} →</Link></div></div>
      <PackageInstallSection locale={locale} />
      <AmlViewDocsSections locale={locale} />
    </div></section>
  </main><Footer locale={locale} /></>;
}
export default function Docs(){return <DocsPage locale="en"/>}
