import Link from "next/link";
import { CodeBlock, Footer, Header } from "../components";

type Locale = "en" | "fr";
const topics = {
  en: [["Get started", "#start"], ["Architecture", "#architecture"], ["CLI reference", "#cli"], ["HTTP & MVC", "#http"], ["Views & assets", "#views"], ["Environment", "#environment"], ["Database", "#database"], ["Security", "#security"], ["Tests & production", "#production"], ["Troubleshooting", "#troubleshooting"]],
  fr: [["Bien démarrer", "#start"], ["Architecture", "#architecture"], ["Référence CLI", "#cli"], ["HTTP et MVC", "#http"], ["Vues et fichiers", "#views"], ["Environnement", "#environment"], ["Base de données", "#database"], ["Sécurité", "#security"], ["Tests et production", "#production"], ["Dépannage", "#troubleshooting"]],
};
const commands = {
  en: [["aml create .", "Create in the current folder"], ["aml create my-project", "Create a new folder"], ["aml install", "Install engine and dependencies"], ["aml serve", "Start localhost:8000 with live reload"], ["aml routes", "List registered routes"], ["aml test", "Run tests/run.php"], ["aml make:controller User", "Generate a controller"], ["aml make:model User", "Generate a model"], ["aml make:middleware Auth", "Generate middleware"], ["aml make:migration create_users_table", "Generate a migration"], ["aml env:init", "Create .env from .env.example"], ["aml env:list", "List variables and mask secrets"], ["aml env:get APP_DEBUG", "Read one variable"], ["aml env:set APP_DEBUG false", "Create or update one variable"], ["aml db:show", "Show database configuration"], ["aml doctor", "Check AML and the project"], ["aml cache:clear", "Clear application cache"], ["aml update --check", "Check for a new release"], ["aml update", "Install the latest release"], ["aml language fr", "Change the CLI language"]],
  fr: [["aml create .", "Créer dans le dossier courant"], ["aml create mon-projet", "Créer un nouveau dossier"], ["aml install", "Installer moteur et dépendances"], ["aml serve", "Démarrer localhost:8000 avec actualisation"], ["aml routes", "Afficher les routes"], ["aml test", "Exécuter tests/run.php"], ["aml make:controller User", "Générer un contrôleur"], ["aml make:model User", "Générer un modèle"], ["aml make:middleware Auth", "Générer un middleware"], ["aml make:migration create_users_table", "Générer une migration"], ["aml env:init", "Créer .env depuis .env.example"], ["aml env:list", "Lister les variables et masquer les secrets"], ["aml env:get APP_DEBUG", "Lire une variable"], ["aml env:set APP_DEBUG false", "Créer ou modifier une variable"], ["aml db:show", "Afficher la configuration de la base"], ["aml doctor", "Vérifier AML et le projet"], ["aml cache:clear", "Vider le cache"], ["aml update --check", "Chercher une nouvelle version"], ["aml update", "Installer la dernière version"], ["aml language en", "Changer la langue du CLI"]],
};

export function DocsPage({ locale }: { locale: Locale }) {
  const fr = locale === "fr", prefix = fr ? "/fr" : "";
  const tx = fr ? { label:"Documentation officielle", title:"Construire avec PHPAML.", accent:"Du premier projet à la production.", lead:"Guide complet de l’environnement autonome AML 1.3.x et du mini-framework MVC PHPAML.", nav:"Dans ce guide" } : { label:"Official documentation", title:"Build with PHPAML.", accent:"From first project to production.", lead:"Complete guide to the autonomous AML 1.3.x environment and the PHPAML MVC mini-framework.", nav:"In this guide" };
  return <><Header locale={locale} path="/docs" /><main>
    <section className="page-hero shell"><p className="eyebrow"><span /> {tx.label}</p><h1>{tx.title}<br /><em>{tx.accent}</em></h1><p>{tx.lead}</p><div className="doc-stats"><span><strong>10</strong>{fr?" chapitres":" chapters"}</span><span><strong>20+</strong>{fr?" commandes":" commands"}</span><span><strong>EN / FR</strong>{fr?" référence bilingue":" bilingual reference"}</span></div></section>
    <section className="docs-layout shell"><aside><strong>{tx.nav}</strong>{topics[locale].map(([n,h])=><a key={h} href={h}>{n}</a>)}</aside><div className="docs-content">
      <section id="start"><span className="doc-label">01 — {fr?"Démarrage":"Getting started"}</span><h2>{fr?"Créer et lancer une application":"Create and run an application"}</h2><p>{fr?"AML inclut son propre PHP et Composer. Après l’installation d’AML, aucune installation globale de PHP, Composer ou Node.js n’est nécessaire.":"AML bundles its own PHP and Composer. After installing AML, no global PHP, Composer, or Node.js installation is required."}</p><CodeBlock>{`aml create ${fr?"mon-projet":"my-project"}\ncd ${fr?"mon-projet":"my-project"}\naml install\naml doctor\naml serve`}</CodeBlock><p>{fr?"Ouvrez ensuite":"Then open"} <code>http://localhost:8000</code>. {fr?"Pour le dossier actuel, utilisez":"For the current folder, use"} <code>aml create .</code></p><div className="notice"><strong>{fr?"Actualisation automatique":"Live reload"}</strong><p>{fr?"Le navigateur se recharge après une modification PHP, CSS, JavaScript, HTML, JSON ou SVG.":"The browser reloads after changes to PHP, CSS, JavaScript, HTML, JSON, or SVG files."}</p></div></section>
      <section id="architecture"><span className="doc-label">02 — Concepts</span><h2>{fr?"Une architecture familière":"A familiar architecture"}</h2><p>{fr?"PHPAML reprend la séparation des responsabilités de Java EE et ASP.NET : contrôleurs, modèles, middleware, injection de dépendances et configuration centrale.":"PHPAML borrows the separation of concerns found in Java EE and ASP.NET: controllers, models, middleware, dependency injection, and central configuration."}</p><div className="file-tree"><pre>{`${fr?"mon-projet":"my-project"}/\n├── app/\n│   ├── Controllers/\n│   ├── Models/\n│   ├── public/{css,js,img}/\n│   └── views/partials/{header,footer}.php\n├── configs/app.php\n├── database/migrations/\n├── tests/\n├── aml_env/\n├── .env\n└── index.php`}</pre></div><p>{fr?"Travaillez dans app, configs, database et tests. aml_env contient le moteur, PHP, Composer et le cache ; ne le modifiez pas manuellement.":"Work in app, configs, database, and tests. aml_env contains the engine, PHP, Composer, and cache; do not edit it manually."}</p><h3>{fr?"Cycle d’une requête":"Request lifecycle"}</h3><ol className="doc-steps"><li><b>index.php</b> {fr?"charge l’environnement et la configuration.":"loads the environment and configuration."}</li><li>{fr?"Les middlewares traitent la requête.":"Middleware processes the request."}</li><li>{fr?"Le routeur extrait les paramètres.":"The router extracts parameters."}</li><li>{fr?"Le conteneur injecte les dépendances du contrôleur.":"The container injects controller dependencies."}</li><li>{fr?"L’action retourne HTML, JSON ou une redirection.":"The action returns HTML, JSON, or a redirect."}</li></ol></section>
      <section id="cli"><span className="doc-label">03 — CLI</span><h2>{fr?"Référence des commandes AML":"AML command reference"}</h2><p>{fr?"Au premier lancement, AML demande English ou Français. Les sorties, diagnostics et erreurs suivent ce choix. AML_LANG=en ou AML_LANG=fr remplace temporairement la langue.":"On first launch, AML asks for English or French. Output, diagnostics, and errors follow that choice. AML_LANG=en or AML_LANG=fr temporarily overrides it."}</p><div className="command-reference">{commands[locale].map(([c,d])=><div key={c}><code>{c}</code><span>{d}</span></div>)}</div><h3>{fr?"Options utiles":"Useful options"}</h3><CodeBlock>{`aml create ${fr?"projet":"project"} --version 0.1.0\naml create ${fr?"projet":"project"} --offline\naml install --production\naml install --refresh\naml doctor --offline\naml doctor --port 8080\naml doctor --json\naml update --version 1.3.0`}</CodeBlock></section>
      <section id="http"><span className="doc-label">04 — HTTP & MVC</span><h2>{fr?"Routes, requêtes et contrôleurs":"Routes, requests, and controllers"}</h2><CodeBlock>{`'GET /users/{id}' => [\n    'handler' => [UserController::class, 'show'],\n    'middleware' => [AuthMiddleware::class],\n    'name' => 'users.show',\n],`}</CodeBlock><CodeBlock>{`public function show(Request $request): Response\n{\n    return $this->json(['id' => $request->attribute('id')]);\n}`}</CodeBlock><p>{fr?"Request fournit method(), path(), query(), input(), cookie(), header(), server() et attribute(). Le JSON est décodé automatiquement. Une route inconnue retourne 404 ; une mauvaise méthode retourne 405.":"Request provides method(), path(), query(), input(), cookie(), header(), server(), and attribute(). JSON is decoded automatically. An unknown route returns 404; an unsupported method returns 405."}</p><CodeBlock>{`return Response::html('<h1>Hello</h1>');\nreturn Response::json(['ok' => true], 201);\nreturn Response::redirect('/login');\nreturn $this->view('users/show.php', ['user' => $user]);`}</CodeBlock></section>
      <section id="views"><span className="doc-label">05 — UI</span><h2>{fr?"Vues, partials et fichiers publics":"Views, partials, and public assets"}</h2><CodeBlock>{`<?php $this->partial('header.php', ['title' => $title]) ?>\n<h1><?= $this->escape($title) ?></h1>\n<?php $this->partial('footer.php') ?>`}</CodeBlock><p>{fr?"Échappez toute valeur non fiable avec $this->escape(). Le moteur bloque les chemins qui sortent de app/views.":"Escape untrusted values with $this->escape(). The engine blocks paths that escape app/views."}</p><CodeBlock>{`<link rel="icon" href="/app/public/img/favicon.svg">\n<link rel="stylesheet" href="/app/public/css/index.css">\n<script src="/app/public/js/main.js"></script>`}</CodeBlock></section>
      <section id="environment"><span className="doc-label">06 — ENV</span><h2>{fr?"Configurer .env en ligne de commande":"Configure .env from the command line"}</h2><CodeBlock>{`aml env:init\naml env:set APP_DEBUG false\naml env:get APP_DEBUG\naml env:list`}</CodeBlock><p>{fr?"env:init copie .env.example ; --force remplace un fichier existant. env:list masque mots de passe, secrets, clés et jetons. Ne publiez jamais .env dans Git.":"env:init copies .env.example; --force replaces an existing file. env:list masks passwords, secrets, keys, and tokens. Never commit .env to Git."}</p></section>
      <section id="database"><span className="doc-label">07 — Data</span><h2>{fr?"SQLite, MySQL et migrations":"SQLite, MySQL, and migrations"}</h2><p>{fr?"SQLite est la base locale par défaut. AML crée aml_env/storage/database.sqlite et enregistre root/root par convention ; SQLite n’utilise pas réellement ces identifiants.":"SQLite is the default local database. AML creates aml_env/storage/database.sqlite and records root/root by convention; SQLite does not actually use these credentials."}</p><CodeBlock>{`aml db:configure sqlite\naml db:configure sqlite --path storage/app.sqlite\naml db:show\n\naml db:configure mysql --host 127.0.0.1 --port 3306 \\\n  --database phpaml --user root --password root`}</CodeBlock><h3>{fr?"Migrations transactionnelles":"Transactional migrations"}</h3><CodeBlock>{`aml make:migration create_users_table\naml migrate`}</CodeBlock><p>{fr?"Les migrations sont enregistrées dans aml_migrations. La version actuelle exécute up(), sans commande rollback. Le QueryBuilder fournit all() et insert() ; utilisez PDO préparé pour le reste.":"Migrations are recorded in aml_migrations. The current version runs up(), with no rollback command. QueryBuilder provides all() and insert(); use prepared PDO for everything else."}</p></section>
      <section id="security"><span className="doc-label">08 — Security</span><h2>{fr?"Validation, CSRF et middleware":"Validation, CSRF, and middleware"}</h2><CodeBlock>{`$valid = $validator->validate($request->input(), [\n  'email' => ['required', 'email'],\n  'name' => ['required', 'string', 'min:2', 'max:100'],\n]);`}</CodeBlock><p>{fr?"Règles : required, email, string, min:n et max:n. Protégez les routes d’écriture avec CsrfMiddleware et ajoutez <?= $this->csrfField() ?> aux formulaires. Pour une API, utilisez X-CSRF-Token.":"Rules: required, email, string, min:n, and max:n. Protect write routes with CsrfMiddleware and add <?= $this->csrfField() ?> to forms. For an API, use X-CSRF-Token."}</p><p>{fr?"SecurityHeadersMiddleware ajoute les en-têtes de sécurité ; les détails d’erreur sont masqués avec APP_DEBUG=false.":"SecurityHeadersMiddleware adds security headers; error details are hidden when APP_DEBUG=false."}</p></section>
      <section id="production"><span className="doc-label">09 — Shipping</span><h2>{fr?"Tester et préparer la production":"Test and prepare for production"}</h2><CodeBlock>{`aml test\naml install --production\naml doctor --json\naml routes`}</CodeBlock><p>{fr?"aml test utilise le PHP privé d’AML et exécute tests/run.php. --production exclut les dépendances de développement et optimise l’autoloader.":"aml test uses AML's private PHP and runs tests/run.php. --production excludes development dependencies and optimizes the autoloader."}</p><div className="notice"><strong>{fr?"Important":"Important"}</strong><p>{fr?"aml serve est réservé au développement. En production : serveur HTTP compatible PHP, HTTPS, APP_DEBUG=false, permissions minimales, sauvegardes et authentification adaptée.":"aml serve is for development only. In production: a PHP-compatible HTTP server, HTTPS, APP_DEBUG=false, minimal permissions, backups, and appropriate authentication."}</p></div></section>
      <section id="troubleshooting"><span className="doc-label">10 — Support</span><h2>{fr?"Résoudre les problèmes fréquents":"Solve common problems"}</h2><div className="faq"><details open><summary>{fr?"La commande aml est introuvable":"The aml command is not found"}</summary><p>{fr?"Ouvrez un nouveau terminal et vérifiez PATH : %LOCALAPPDATA%\\Programs\\PHPAML\\bin sous Windows, /usr/local/bin sous macOS/Linux.":"Open a new terminal and check PATH: %LOCALAPPDATA%\\Programs\\PHPAML\\bin on Windows, /usr/local/bin on macOS/Linux."}</p></details><details><summary>{fr?"L’environnement AML est absent":"The AML environment is missing"}</summary><p>{fr?"Depuis la racine du projet, lancez aml install.":"From the project root, run aml install."}</p></details><details><summary>{fr?"CSS ou JavaScript ne se charge pas":"CSS or JavaScript does not load"}</summary><p>{fr?"Vérifiez /app/public/, les majuscules du fichier et lancez aml serve depuis le dossier contenant index.php.":"Check /app/public/, filename casing, and run aml serve from the folder containing index.php."}</p></details><details><summary>{fr?"Le port 8000 est occupé":"Port 8000 is busy"}</summary><p><code>aml doctor --port 8080</code><br/><code>aml serve 127.0.0.1:8080</code></p></details><details><summary>{fr?"GitHub est inaccessible":"GitHub is unavailable"}</summary><p>{fr?"Utilisez aml create projet --offline ou aml install --offline pour réutiliser le cache.":"Use aml create project --offline or aml install --offline to reuse the cache."}</p></details></div></section>
      <div className="docs-next"><span>{fr?"Prêt à construire votre première application ?":"Ready to build your first application?"}</span><Link href={`${prefix}/download`}>{fr?"Installer AML":"Install AML"} →</Link></div>
    </div></section>
  </main><Footer locale={locale} /></>;
}
export default function Docs(){return <DocsPage locale="en"/>}
