"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { NewsArticleRenderer } from "../../news-article-renderer";

type Post = { slug: string; status: "draft" | "published"; published_at: string | null; version: string; title_en: string; summary_en: string; content_en: string; title_fr: string; summary_fr: string; content_fr: string };
const empty: Post = { slug: "", status: "draft", published_at: null, version: "", title_en: "", summary_en: "", content_en: "", title_fr: "", summary_fr: "", content_fr: "" };

export function AdminNews({ adminName }: { adminName: string }) {
  const [posts, setPosts] = useState<Post[]>([]), [form, setForm] = useState<Post>(empty), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [mode, setMode] = useState<"edit" | "preview">("edit"), [previewLocale, setPreviewLocale] = useState<"en" | "fr">("fr");
  const load = useCallback(async () => { const response = await fetch("/api/admin/news", { cache: "no-store" }); const data = await response.json(); setPosts(data.posts ?? []); }, []);
  useEffect(() => { let active = true; fetch("/api/admin/news", { cache: "no-store" }).then((response) => response.json()).then((data) => { if (active) setPosts(data.posts ?? []); }); return () => { active = false; }; }, []);
  const field = (key: keyof Post) => ({ value: form[key] ?? "", onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setForm({ ...form, [key]: event.target.value }) });
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); try { const response = await fetch("/api/admin/news", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? (form.status === "published" ? "Publication mise en ligne." : "Brouillon enregistré.") : data.error ?? `Échec de l’enregistrement (${response.status}).`); if (response.ok) await load(); } catch { setMessage("Le service de publication est momentanément indisponible."); } finally { setBusy(false); } }
  async function remove(slug: string) { if (!window.confirm(`Supprimer définitivement ${slug} ?`)) return; const response = await fetch(`/api/admin/news?slug=${encodeURIComponent(slug)}`, { method: "DELETE" }); if (!response.ok) { setMessage("La suppression a échoué."); return; } if (form.slug === slug) setForm(empty); await load(); }
  const previewPost = { slug: form.slug || "preview", date: form.published_at || new Date().toISOString().slice(0, 10), version: form.version, translation: previewLocale === "fr" ? { category: "Actualité", title: form.title_fr, summary: form.summary_fr, content: form.content_fr } : { category: "News", title: form.title_en, summary: form.summary_en, content: form.content_en } };
  return <main className="admin-news-page"><header className="admin-top"><div><small>PHPAML / ADMIN</small><h1>Publications</h1><p>Connecté : {adminName}</p></div><div className="admin-top-actions"><Link href="/news">Voir News ↗</Link><form action="/api/admin/logout" method="post"><button type="submit">Déconnexion</button></form></div></header><div className="admin-layout">
    <aside><div className="admin-list-head"><strong>Actualités</strong><button type="button" onClick={() => { setForm(empty); setMode("edit"); }}>+ Nouvelle</button></div>{posts.length === 0 && <p className="admin-empty">Aucune publication.</p>}{posts.map((post) => <article key={post.slug}><button type="button" onClick={() => { setForm(post); setMode("edit"); }}><span className={`admin-status ${post.status}`}>{post.status}</span><strong>{post.title_fr}</strong><small>{post.slug}</small></button><button className="admin-delete" aria-label={`Supprimer ${post.title_fr}`} type="button" onClick={() => void remove(post.slug)}>×</button></article>)}</aside>
    <form onSubmit={submit}><div className="admin-form-head"><div><small>ÉDITEUR BILINGUE</small><h2>{form.slug ? "Modifier" : "Nouvelle actualité"}</h2></div><div><button className="admin-secondary" type="button" onClick={() => setMode(mode === "edit" ? "preview" : "edit")}>{mode === "edit" ? "Aperçu" : "Éditer"}</button><select aria-label="Statut" {...field("status")}><option value="draft">Brouillon</option><option value="published">Publié</option></select><button disabled={busy} type="submit">{busy ? "Enregistrement…" : form.status === "published" ? "Publier" : "Enregistrer"}</button></div></div>{message && <p className="admin-message">{message}</p>}
      {mode === "preview" && <div className="admin-preview"><div className="admin-preview-tools"><strong>Rendu public</strong><div><button className={previewLocale === "en" ? "active" : ""} type="button" onClick={() => setPreviewLocale("en")}>EN</button><button className={previewLocale === "fr" ? "active" : ""} type="button" onClick={() => setPreviewLocale("fr")}>FR</button></div></div><div className="news-article-page"><NewsArticleRenderer locale={previewLocale} post={previewPost} preview /></div></div>}
      <div hidden={mode === "preview"}>
      <div className="admin-basics"><label>Slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="nouvelle-version-phpaml" {...field("slug")} /></label><label>Version<input placeholder="1.8.0-beta.1" {...field("version")} /></label><label>Date de publication<input type="date" {...field("published_at")} /></label></div>
      <div className="admin-format-help"><strong>Format du contenu</strong><span><code>## Titre</code> · <code>- liste</code> · <code>&gt; citation</code> · <code>```php</code> bloc de code</span></div>
      <div className="admin-languages"><fieldset><legend><span>EN</span> English</legend><label>Title<input required {...field("title_en")} /></label><label>Summary<textarea required rows={3} {...field("summary_en")} /></label><label>Content<textarea required rows={16} placeholder="Write paragraphs, ## headings, lists, quotes and code blocks." {...field("content_en")} /></label></fieldset><fieldset><legend><span>FR</span> Français</legend><label>Titre<input required {...field("title_fr")} /></label><label>Résumé<textarea required rows={3} {...field("summary_fr")} /></label><label>Contenu<textarea required rows={16} placeholder="Écrivez des paragraphes, titres ##, listes, citations et blocs de code." {...field("content_fr")} /></label></fieldset></div>
      </div>
    </form>
  </div></main>;
}
