import Link from "next/link";
import { CodeBlock, Footer, Header } from "../components";
import "./chapter-one.css";
import "./chapter-four.css";

const examples=[
`Route::get('/books', [BookController::class, 'index']);`,
`Route::get('/books/{id}', [BookController::class, 'show'])\n    ->whereNumber('id');`,
`$url = route('books.show', ['id' => $book->id]);`,
`Route::prefix('/admin')\n    ->middleware(['auth', 'role:editor'])\n    ->group(function (): void {\n        Route::patch('/books/{id}', [BookController::class, 'update']);\n        Route::delete('/books/{id}', [BookController::class, 'destroy']);\n    });`,
];
const crudRoutes=`Route::get('/books', [BookController::class, 'index'])->name('books.index');
Route::get('/books/create', [BookController::class, 'create'])->name('books.create');
Route::post('/books', [BookController::class, 'store'])->name('books.store');
Route::get('/books/{id}', [BookController::class, 'show'])->name('books.show');
Route::get('/books/{id}/edit', [BookController::class, 'edit'])->name('books.edit');
Route::patch('/books/{id}', [BookController::class, 'update'])->name('books.update');
Route::delete('/books/{id}', [BookController::class, 'destroy'])->name('books.destroy');`;

export function ChapterFour({locale}:{locale:"en"|"fr"}){
 const fr=locale==="fr", prefix=fr?"/fr":"";
 const lessons=fr?[
 ["04.1","Une route est un contrat","Une route ne signifie pas seulement « cette URL ouvre cette page ». Elle définit un contrat entre le client et l’application : une méthode, un chemin, des paramètres, des protections et une action.",["GET /books promet de consulter la collection. POST /books promet de traiter une création. Ils partagent le même chemin, mais leurs intentions et leurs réponses sont différentes.","Une route doit permettre de comprendre l’interface HTTP sans lire le contrôleur. Une requête SQL, du HTML ou de longues conditions y mélangeraient des responsabilités."],"Prononcez toujours la méthode et le chemin : GET /books, pas seulement /books."],
 ["04.2","Choisir la méthode HTTP","La méthode annonce l’effet attendu. GET consulte, POST crée ou déclenche, PATCH modifie une partie et DELETE supprime.",["GET doit rester sans effet métier volontaire : actualiser la page ne doit jamais créer un second livre. Navigateurs, caches et robots dépendent de cette propriété.","POST n’est pas un GET plus puissant. PATCH /books/42 cible une ressource existante; DELETE /books/42 exprime clairement sa suppression."],"Une action déclenchée par un lien normal doit généralement être GET et ne jamais supprimer."],
 ["04.3","Concevoir les URL","Une URL décrit une ressource, pas l’implémentation PHP. Préférez /books/42 à /showBook.php?id=42.",["Utilisez des noms pluriels cohérents pour les collections. L’identifiant sélectionne un membre. Un sous-chemin représente une page ou une relation lorsque la méthode seule ne suffit pas.","Une bonne URL reste stable si BookController change, si SQLite devient MongoDB ou si la vue classique devient AML View."],"Évitez les verbes techniques lorsque la méthode HTTP exprime déjà l’action."],
 ["04.4","Paramètres dynamiques et contraintes","Dans /books/{id}, id est extrait du chemin. Le routeur sait que /books/42 peut correspondre, mais vous devez encore définir les valeurs acceptables.",["Une contrainte numérique empêche /books/bonjour d’atteindre un contrôleur qui attend un entier. Elle ne remplace pas la validation métier : 42 peut être bien formé mais désigner un livre absent.","Distinguez route non trouvée, paramètre invalide et ressource absente. Cette précision améliore statuts, journaux et tests."],"Validez la forme tôt, puis l’existence et les règles dans la couche appropriée."],
 ["04.5","Routes nommées et URL","Une route nommée fournit un identifiant stable comme books.show. La vue génère alors le lien sans recopier /books/{id}.",["Si le chemin devient /library/books/{id}, tous les appels par nom survivent après une seule modification.","Le nom décrit la destination applicative et suit une convention régulière resource.action, indépendante du texte visible."],"Une route nommée centralise un contrat qui serait autrement recopié dans plusieurs vues."],
 ["04.6","Groupes, préfixes et middlewares","Un groupe applique une propriété commune : préfixe /admin, middleware auth ou espace de noms.",["Regrouper évite de répéter les protections et rend la politique visible. Toutes les routes d’administration peuvent exiger une session; l’édition peut demander un rôle supplémentaire.","L’ordre des middlewares importe. Les en-têtes de sécurité doivent également couvrir les réponses anticipées 401, 403 et 429."],"Déclarez une protection commune au niveau commun le plus proche, sans la rendre invisible."],
 ["04.7","Séparer web et API","Web et API peuvent partager les modèles, mais leurs contrats de réponse diffèrent.",["Le web utilise souvent sessions, CSRF, redirections et HTML. Une API utilise JSON, jetons, statuts explicites et un préfixe versionné comme /api/v1.","Partagez les règles métier par les modèles ou services, puis laissez chaque surface adapter Request et Response à son client."],"Partager le métier ne signifie pas mélanger les contrats HTTP du navigateur et de l’API."],
 ["04.8","Organiser les fichiers","Un petit projet tient dans routes/webapp.php. Un fichier de plusieurs centaines de lignes devient une carte illisible.",["Regroupez par surface ou fonctionnalité : webapp.php, api.php, admin.php, puis MovieRoute lorsque l’API adopte une route par contrôleur.","Le chargement doit rester découvrable. Évitez une magie qui parcourt tous les fichiers sans convention explicite."],"Créez un fichier pour clarifier une frontière réelle, pas pour remplir des dossiers vides."],
 ["04.9","Distinguer 404 et 405","404 indique qu’aucune route ou ressource correspondante n’existe. 405 indique que le chemin existe, mais pas pour la méthode reçue.",["GET /books/42 peut produire 404 si le livre est absent. POST /books/42 produit 405 si seules GET, PATCH et DELETE sont autorisées.","Cette distinction aide le client à corriger sa requête. Une réponse 405 peut annoncer les méthodes acceptées avec Allow."],"Diagnostiquez le couple méthode-chemin avant l’existence de la ressource."],
 ["04.10","Tester la carte","Une route n’est terminée que lorsque son contrat est vérifié : succès, mauvaise méthode, paramètre invalide, ressource absente et protection middleware.",["Observez les statuts, en-têtes, redirections et contenus essentiels sans lier les tests à des détails visuels inutiles.","Vérifiez aussi qu’une route sensible reste inaccessible sans authentification. Une bonne action avec le mauvais middleware reste une faille."],"Chaque branche importante du contrat HTTP mérite un test reproductible."],
 ]:[
 ["04.1","A route is a contract","A route means more than an URL opening a page. It defines a client contract: method, path, parameters, protection, and action.",["GET /books promises to read the collection. POST /books promises creation. They share a path but expose different intentions and responses.","The HTTP interface should be understandable without reading controller code. SQL, HTML, and long conditions do not belong in routes."],"Always say method and path: GET /books, not only /books."],
 ["04.2","Choose the HTTP method","The method announces the effect. GET reads, POST creates or triggers, PATCH partially changes, and DELETE removes.",["GET must avoid intentional business side effects: refreshing must never create another book.","POST is not a stronger GET. PATCH /books/42 targets an existing resource; DELETE expresses removal."],"A normal link should generally be GET and never delete data."],
 ["04.3","Design URLs","An URL describes a resource, not PHP implementation. Prefer /books/42 over /showBook.php?id=42.",["Use consistent plural collection names. An identifier selects one member; subpaths represent pages or relationships.","A good URL survives controller, database, and view replacements."],"Avoid technical verbs when the HTTP method already expresses the action."],
 ["04.4","Dynamic parameters and constraints","In /books/{id}, id comes from the path. You must still define acceptable values.",["A numeric constraint keeps /books/hello away from an integer controller. It does not replace business validation: 42 may be valid but absent.","Distinguish no route, invalid parameter, and missing resource."],"Validate shape early, then existence and rules in the appropriate layer."],
 ["04.5","Named routes and URLs","A named route provides a stable identifier such as books.show so views do not copy /books/{id}.",["When the path changes, name-based calls survive one declaration update.","Use a regular resource.action convention independent of visible labels."],"A name centralizes a contract otherwise copied into many views."],
 ["04.6","Groups, prefixes, and middleware","A group applies a common /admin prefix, auth middleware, or namespace.",["Grouping avoids repeated protection and makes policy visible.","Middleware order matters. Security headers must also cover early 401, 403, and 429 responses."],"Declare shared protection at the nearest shared level without hiding it."],
 ["04.7","Separate web and API","Web and API can share models while exposing different response contracts.",["Web commonly uses sessions, CSRF, redirects, and HTML. APIs use JSON, tokens, explicit statuses, and /api/v1.","Share business rules through models or services while each surface adapts Request and Response."],"Shared business logic does not mean mixed HTTP contracts."],
 ["04.8","Organize files","A small project fits routes/webapp.php. Hundreds of entries become an unreadable map.",["Group by surface or feature: webapp.php, api.php, admin.php, then MovieRoute for route-per-controller APIs.","Keep loading discoverable and avoid unexplained filesystem magic."],"Add a file to clarify a real boundary, not to populate empty folders."],
 ["04.9","Distinguish 404 and 405","404 means no matching route or resource. 405 means the path exists but not for the received method.",["GET /books/42 can be 404 when absent. POST /books/42 is 405 when only GET, PATCH, and DELETE exist.","A 405 may announce accepted methods with Allow."],"Diagnose method-path before resource existence."],
 ["04.10","Test the map","A route is complete only when success, wrong methods, invalid parameters, missing resources, and middleware are verified.",["Observe statuses, headers, redirects, and essential content without irrelevant visual coupling.","Verify sensitive routes remain inaccessible without authentication."],"Every important contract branch deserves a reproducible test."],
 ];
 const matrix=[["GET","/books","index","200"],["GET","/books/create","create","200"],["POST","/books","store","201 / 302"],["GET","/books/{id}","show","200 / 404"],["GET","/books/{id}/edit","edit","200 / 404"],["PATCH","/books/{id}","update","200 / 302"],["DELETE","/books/{id}","destroy","204 / 302"]];
 return <><Header locale={locale} path="/tutorial/04"/><main className="lesson-page routes-lesson">
 <section className="lesson-hero shell"><div><p className="eyebrow"><span/> {fr?"Tutoriel MVC · Chapitre 04":"MVC tutorial · Chapter 04"}</p><h1>{fr?<>Définir et organiser<br/><em>les routes.</em></>:<>Define and organize<br/><em>routes.</em></>}</h1><p>{fr?"Construisez la carte HTTP complète d’une bibliothèque et apprenez à la garder lisible, sécurisée et testable lorsqu’elle grandit.":"Build a library's complete HTTP map and keep it readable, secure, and testable as it grows."}</p></div><aside><small>{fr?"OBJECTIF":"OUTCOME"}</small><strong>{fr?"Une carte CRUD prête pour les contrôleurs":"A CRUD map ready for controllers"}</strong><span>≈ 110 min</span></aside></section>
 <section className="route-equation shell"><span>METHOD</span><b>+</b><span>PATH</span><b>+</b><span>POLICY</span><b>→</b><strong>ACTION</strong></section>
 <div className="lesson-layout shell"><nav className="lesson-toc"><strong>{fr?"Dans ce chapitre":"In this chapter"}</strong>{lessons.map(x=><a href={`#section-${x[0]}`} key={x[0]}><span>{x[0]}</span>{x[1] as string}</a>)}<a href="#workshop"><span>✓</span>{fr?"Projet final":"Final project"}</a></nav><article className="lesson-content">
 <div className="lesson-callout"><strong>{fr?"Projet du chapitre":"Chapter project"}</strong><p>{fr?"Concevez toutes les routes pour consulter, créer, modifier et supprimer les livres, puis vérifiez leurs contrats HTTP.":"Design every route for browsing, creating, updating, and deleting books, then verify their HTTP contracts."}</p></div>
 <section className="route-map"><p className="kicker">{fr?"Carte cible":"Target map"}</p><h2>{fr?"Sept routes, une ressource cohérente.":"Seven routes, one coherent resource."}</h2><div>{matrix.map(([m,p,a,s])=><div key={m+p}><strong>{m}</strong><code>{p}</code><span>{a}</span><small>{s}</small></div>)}</div></section>
 {lessons.map((x,index)=><section className="lesson-section route-lesson-part" id={`section-${x[0]}`} key={x[0]}><span className="lesson-number">{x[0]}</span><h2>{x[1] as string}</h2><p className="route-lead">{x[2] as string}</p>{(x[3] as string[]).map(p=><p key={p}>{p}</p>)}<div className="route-understand"><strong>{fr?"Principe à retenir":"Principle to retain"}</strong><p>{x[4] as string}</p></div>{index===0&&<CodeBlock>{examples[0]}</CodeBlock>}{index===3&&<CodeBlock>{examples[1]}</CodeBlock>}{index===4&&<CodeBlock>{examples[2]}</CodeBlock>}{index===5&&<CodeBlock>{examples[3]}</CodeBlock>}{index===6&&<div className="web-api-compare"><div><strong>WEB</strong><span>Session · CSRF · HTML · Redirect</span><code>routes/webapp.php</code></div><div><strong>API</strong><span>Token · JSON · Status · /api/v1</span><code>routes/api.php</code></div></div>}{index===8&&<div className="error-split"><div><strong>404</strong><span>{fr?"chemin ou ressource absente":"missing path or resource"}</span></div><div><strong>405</strong><span>{fr?"méthode non permise":"method not allowed"}</span></div></div>}</section>)}
 <section className="crud-code"><p className="kicker">{fr?"Assemblage":"Assembly"}</p><h2>{fr?"La carte CRUD complète.":"The complete CRUD map."}</h2><p>{fr?"Lisez-la comme une table des matières HTTP. Chaque déclaration doit conduire à une méthode de contrôleur courte et précise.":"Read it as an HTTP table of contents. Every declaration should lead to a short, focused controller method."}</p><CodeBlock>{crudRoutes}</CodeBlock></section>
 <section className="lesson-exercise" id="workshop"><p className="kicker">{fr?"Projet final":"Final project"}</p><h2>{fr?"Construisez et testez BookRoute.":"Build and test BookRoute."}</h2><ol><li>{fr?"Écrivez les sept routes CRUD sans logique métier.":"Write seven CRUD routes without business logic."}</li><li>{fr?"Nommez-les avec books.action.":"Name them using books.action."}</li><li>{fr?"Contraignez id à un entier positif.":"Constrain id to a positive integer."}</li><li>{fr?"Protégez création, modification et suppression.":"Protect creation, update, and deletion."}</li><li>{fr?"Ajoutez la version JSON /api/v1/books.":"Add the /api/v1/books JSON version."}</li><li>{fr?"Testez succès, 404, 405, validation et accès refusé.":"Test success, 404, 405, validation, and denied access."}</li></ol></section>
 <section className="lesson-rich-block lesson-correction"><p className="kicker">{fr?"Correction raisonnée":"Reasoned solution"}</p><h2>{fr?"Vérifiez les contrats, pas seulement la syntaxe.":"Verify contracts, not only syntax."}</h2><p>{fr?"La qualité dépend des frontières : aucune requête de base dans routes, aucun secret, méthodes cohérentes, noms stables, contraintes explicites et protections visibles.":"Quality depends on boundaries: no database query in routes, no secrets, coherent methods, stable names, explicit constraints, and visible protection."}</p><details><summary>{fr?"Pourquoi /books/create si POST /books crée ?":"Why /books/create when POST /books creates?"}</summary><p>{fr?"GET /books/create affiche le formulaire sans modifier les données. POST /books traite ensuite sa soumission.":"GET /books/create displays the form without changing data. POST /books then processes its submission."}</p></details><details><summary>{fr?"Faut-il une route par contrôleur ?":"Should there be one route class per controller?"}</summary><p>{fr?"Pour une API moyenne, MovieRoute avec MovieController est lisible. Pour un petit site, webapp.php suffit. Choisissez ce qui facilite la découverte sans créer de dossiers vides.":"For a medium API, MovieRoute with MovieController is clear. For a small site, webapp.php is enough. Optimize discovery without empty folders."}</p></details></section>
 </article></div><section className="lesson-navigation shell"><Link href={`${prefix}/tutorial/03`}>← {fr?"Chapitre 03":"Chapter 03"}</Link><span>{fr?"Chapitre 05 · À venir":"Chapter 05 · Coming soon"} 🔒</span></section>
 </main><Footer locale={locale}/></>;
}
