import Link from "next/link";
import { CodeBlock, Footer, Header } from "../components";
import "./chapter-one.css";
import "./chapter-four.css";
import "./chapter-six.css";

type Lesson = {
  n: string;
  fr: string;
  en: string;
  frText: string[];
  enText: string[];
  frRule: string;
  enRule: string;
};

const lessons: Lesson[] = [
  {n:"06.1",fr:"Comprendre le rôle d’une vue",en:"Understand the role of a view",frText:["Une vue transforme les données préparées par le contrôleur en document destiné à l’utilisateur. Dans une application Web classique, ce document est généralement du HTML accompagné de liens, formulaires et messages.","La vue ne décide pas quelles tâches appartiennent à l’utilisateur et ne lance pas la création d’une ressource. Ces décisions ont déjà été prises avant le rendu. Elle reçoit un contrat de données et se concentre sur leur présentation.","Cette séparation permet de modifier le design sans réécrire les règles métier et de tester le contrôleur sans analyser toute la mise en page."],enText:["A view turns controller-prepared data into a document for the user. In a classic Web application, that document is usually HTML with links, forms, and messages.","The view does not decide which tasks belong to the user and does not create resources. Those decisions were made before rendering. It receives a data contract and focuses on presentation.","This separation lets design change without rewriting business rules and lets controllers be tested without parsing the full layout."],frRule:"La vue présente une décision déjà prise; elle ne remplace ni le contrôleur ni le modèle.",enRule:"A view presents an existing decision; it replaces neither controller nor model."},
  {n:"06.2",fr:"Transmettre les données explicitement",en:"Pass data explicitly",frText:["Le second argument de view() constitue le contrat entre le contrôleur et le template. Chaque clé devient une variable disponible au rendu : tasks, title, currentFilter ou permissions.","Choisissez des noms qui décrivent le contenu, pas son apparence. tasks restera pertinent si la liste devient une grille; leftColumnTasks enfermerait la vue dans un design particulier.","Évitez les variables magiques disponibles partout sans déclaration. Un contrat explicite permet de savoir ce dont une vue dépend et produit une erreur compréhensible lorsqu’une donnée manque."],enText:["The second argument of view() is the contract between controller and template. Each key becomes a render variable: tasks, title, currentFilter, or permissions.","Choose names that describe content rather than appearance. tasks remains useful if a list becomes a grid; leftColumnTasks couples data to one design.","Avoid magical globally available variables. An explicit contract reveals dependencies and produces an understandable error when data is missing."],frRule:"Une vue doit annoncer ses dépendances par les données que le contrôleur lui transmet.",enRule:"A view should reveal its dependencies through controller-supplied data."},
  {n:"06.3",fr:"Échapper toutes les sorties",en:"Escape every output",frText:["Une valeur venant d’un utilisateur peut contenir du HTML ou du JavaScript. L’afficher directement permettrait à ce contenu de devenir une partie active de la page : c’est une vulnérabilité XSS.","Échappez le titre, la description, le nom et toute autre valeur dynamique selon le contexte HTML. L’échappement d’un texte, d’un attribut, d’une URL et d’un script ne suit pas exactement les mêmes règles.","N’utilisez une sortie HTML brute que pour un contenu explicitement approuvé et nettoyé. Le simple fait qu’une valeur provienne de la base ne la rend pas sûre : elle a pu être dangereuse avant son enregistrement."],enText:["A user value can contain HTML or JavaScript. Printing it directly lets that content become active page code, creating an XSS vulnerability.","Escape titles, descriptions, names, and every dynamic value for its HTML context. Text, attributes, URLs, and scripts do not have exactly the same escaping rules.","Use raw HTML only for explicitly trusted and sanitized content. Database origin does not make a value safe; it may have been dangerous before storage."],frRule:"Validez à l’entrée pour le métier; échappez à la sortie pour le contexte d’affichage.",enRule:"Validate input for business rules; escape output for its display context."},
  {n:"06.4",fr:"Afficher conditions et collections",en:"Render conditions and collections",frText:["Une liste de tâches doit gérer au moins trois états : chargement réussi avec résultats, collection vide et parfois erreur de récupération. Une vue robuste rend chacun de ces états intentionnellement.","Dans la boucle, donnez à chaque élément une structure cohérente et limitez les décisions au rendu : afficher le badge terminé, la date ou le bouton permis. Une règle comme déterminer si la tâche est en retard doit idéalement être préparée par le modèle.","L’état vide n’est pas une erreur technique. Il guide l’utilisateur vers sa première action avec un texte utile et un lien vers le formulaire de création."],enText:["A task list needs at least three states: successful loading with results, an empty collection, and sometimes a loading error. A robust view renders each state intentionally.","Inside the loop, give each item consistent structure and keep decisions presentational: show a completed badge, date, or permitted button. A rule such as deciding whether a task is overdue should ideally be prepared by the model.","Empty state is not a technical error. It guides the user toward a first action with useful copy and a creation link."],frRule:"Chaque état possible des données doit posséder une présentation volontaire.",enRule:"Every possible data state deserves an intentional presentation."},
  {n:"06.5",fr:"Extraire des partials réutilisables",en:"Extract reusable partials",frText:["Un partial est un fragment de présentation réutilisé dans plusieurs pages : header, navigation, footer, message flash ou carte de tâche. Il évite la duplication tout en conservant du HTML simple.","Extrayez un fragment lorsqu’il représente une unité reconnaissable ou lorsqu’une modification devrait s’appliquer partout. Ne découpez pas chaque balise dans son propre fichier : une fragmentation excessive rend la page plus difficile à suivre.","Transmettez au partial les données dont il a besoin. Une carte Task reçoit une tâche et les permissions pertinentes; elle ne devrait pas chercher silencieusement l’utilisateur ou interroger la base."],enText:["A partial is presentation reused by several pages: header, navigation, footer, flash message, or task card. It removes duplication while preserving simple HTML.","Extract a fragment when it is a recognizable unit or when one change should apply everywhere. Do not put every tag in a separate file; excessive fragmentation makes pages harder to follow.","Pass the data a partial needs. A Task card receives a task and relevant permissions; it should not secretly find the user or query the database."],frRule:"Un bon partial possède une responsabilité visuelle claire et un petit contrat de données.",enRule:"A good partial has one clear visual responsibility and a small data contract."},
  {n:"06.6",fr:"Construire un layout commun",en:"Build a shared layout",frText:["Le layout contient le squelette stable du document : doctype, langue, métadonnées, feuilles de style, header, zone principale et footer. Les pages fournissent ensuite leur contenu spécifique.","Centraliser ce squelette garantit que toutes les pages reçoivent les mêmes fondations d’accessibilité et de sécurité. Le titre et la description peuvent toutefois varier selon la route.","Placez les ressources communes une seule fois et gardez une zone explicite pour le contenu. Un layout ne doit pas cacher des appels métier ou imposer des données que certaines pages ne possèdent pas."],enText:["The layout contains the stable document skeleton: doctype, language, metadata, stylesheets, header, main area, and footer. Pages then provide specific content.","Centralizing this skeleton gives every page the same accessibility and security foundations. Title and description can still vary by route.","Load shared assets once and keep an explicit content slot. A layout should not hide business calls or require data that some pages do not have."],frRule:"Le layout centralise la structure commune sans effacer l’identité de chaque page.",enRule:"The layout centralizes shared structure without erasing each page's identity."},
  {n:"06.7",fr:"Créer les formulaires",en:"Build forms",frText:["Le formulaire create envoie une nouvelle tâche vers store. Le formulaire edit envoie les modifications vers update. Leur action et leur méthode doivent correspondre exactement aux routes définies au chapitre 4.","Chaque champ possède un label lié, une valeur précédente, une indication utile et une zone d’erreur. Le bouton décrit l’action : Créer la tâche ou Enregistrer les modifications, plutôt qu’un vague Envoyer.","Incluez le jeton CSRF dans toute mutation Web. Pour PATCH et DELETE, utilisez le mécanisme de substitution de méthode du framework lorsque le navigateur ne peut envoyer directement que GET et POST."],enText:["The create form sends a new task to store. The edit form sends changes to update. Their action and method must match the routes defined in chapter 4.","Every field has a connected label, previous value, useful hint, and error area. The button describes the action: Create task or Save changes rather than vague Submit.","Include the CSRF token in every Web mutation. For PATCH and DELETE, use the framework's method override when browsers can only submit GET and POST directly."],frRule:"Un formulaire est une interface vers un contrat HTTP, pas seulement un groupe de champs.",enRule:"A form is an interface to an HTTP contract, not merely a group of fields."},
  {n:"06.8",fr:"Afficher les erreurs de validation",en:"Display validation errors",frText:["Lorsqu’une saisie est invalide, l’utilisateur doit comprendre ce qui s’est passé, où corriger et comment réussir. Une bordure rouge sans texte n’est pas une explication suffisante.","Affichez un résumé en haut lorsque plusieurs erreurs existent, puis le message précis près de chaque champ. Associez le message au contrôle avec les attributs accessibles appropriés.","Réaffichez l’ancienne saisie pour éviter de forcer l’utilisateur à tout recommencer, sauf pour les données sensibles comme les mots de passe. Conservez un langage humain plutôt que les noms internes de colonnes."],enText:["When input is invalid, users must understand what happened, where to fix it, and how to succeed. A red border without text is not enough.","Show a summary near the top when several errors exist, then a precise message beside each field. Associate messages with controls using appropriate accessibility attributes.","Restore previous input so users do not start over, except sensitive data such as passwords. Use human language rather than internal column names."],frRule:"Une erreur utile explique le problème et rapproche l’utilisateur de la solution.",enRule:"A useful error explains the problem and moves the user toward the solution."},
  {n:"06.9",fr:"Utiliser les messages flash",en:"Use flash messages",frText:["Après une redirection, le nouveau document ne possède plus naturellement le résultat de la requête précédente. Un message flash transporte cette information pendant une seule requête.","Utilisez-le pour confirmer une création, modification ou suppression, et parfois pour annoncer un avertissement. Le message doit être bref, spécifique et visible sans bloquer la navigation.","Le partial flash peut choisir un style selon success, warning ou error. Il doit aussi rester compréhensible sans dépendre uniquement d’une couleur et être annoncé correctement aux technologies d’assistance."],enText:["After a redirect, the new document no longer naturally knows the previous request's result. A flash message carries that information for one request.","Use it to confirm creation, update, or deletion, and sometimes to announce a warning. Keep it short, specific, and visible without blocking navigation.","A flash partial can style success, warning, or error. It must remain understandable without color alone and be announced properly to assistive technology."],frRule:"Le flash confirme une transition; il ne remplace pas le contenu durable de la page.",enRule:"Flash confirms a transition; it does not replace durable page content."},
  {n:"06.10",fr:"Tester le rendu et l’accessibilité",en:"Test rendering and accessibility",frText:["Un test de vue vérifie que les données importantes apparaissent, que les valeurs dangereuses sont échappées et que les états vide et erreur sont présents. Il ne doit pas dépendre de chaque classe CSS.","Testez les liens et actions de formulaires afin qu’ils suivent les routes nommées. Vérifiez également labels, hiérarchie des titres, langue du document, texte alternatif et navigation au clavier.","Complétez les tests automatisés par une lecture réelle sur mobile et tablette. Une page techniquement valide peut rester inutilisable si le formulaire déborde ou si le message d’erreur est invisible."],enText:["A view test checks that important data appears, dangerous values are escaped, and empty and error states exist. It should not depend on every CSS class.","Test form links and actions against named routes. Also verify labels, heading hierarchy, document language, alternative text, and keyboard navigation.","Complement automation with real mobile and tablet reading. A technically valid page can remain unusable when a form overflows or an error is invisible."],frRule:"Testez ce que l’utilisateur peut lire, comprendre et accomplir.",enRule:"Test what users can read, understand, and accomplish."},
];

const controllerCode=`return view('tasks/index', [
    'title' => 'My tasks',
    'tasks' => $tasks,
    'canCreate' => $request->user()->can('create', Task::class),
]);`;
const escapedCode=`<h2><?= e($task->title) ?></h2>
<p><?= e($task->description) ?></p>`;
const listCode=`<?php if (empty($tasks)): ?>
  <section class="empty-state">
    <h2>No tasks yet</h2>
    <a href="<?= route('tasks.create') ?>">Create your first task</a>
  </section>
<?php else: ?>
  <?php foreach ($tasks as $task): ?>
    <?php view('tasks/_card', ['task' => $task]); ?>
  <?php endforeach; ?>
<?php endif; ?>`;
const formCode=`<form method="POST" action="<?= route('tasks.store') ?>">
  <?= csrf_field() ?>
  <label for="title">Task title</label>
  <input id="title" name="title"
         value="<?= e(old('title')) ?>"
         aria-describedby="title-error">
  <?php if ($errors->has('title')): ?>
    <p id="title-error" role="alert">
      <?= e($errors->first('title')) ?>
    </p>
  <?php endif; ?>
  <button type="submit">Create task</button>
</form>`;

function Opening({fr}:{fr:boolean}) {
  return <section className="lesson-rich-block course-opening">
    <h2>{fr?"Les données existent. Il faut maintenant les rendre compréhensibles.":"The data exists. Now it must become understandable."}</h2>
    <p>{fr?"Les routes savent reconnaître les demandes et les contrôleurs savent préparer les réponses. Mais un tableau PHP contenant des tâches ne constitue pas encore une expérience utilisateur. Il faut organiser les informations, créer une hiérarchie visuelle, proposer les bonnes actions et expliquer clairement les erreurs.":"Routes can recognize requests and controllers can prepare responses. But a PHP array containing tasks is not yet a user experience. Information must be organized, visual hierarchy created, correct actions offered, and errors explained clearly."}</p>
    <p>{fr?"C’est le rôle de la couche View. Elle se trouve à la frontière entre les données internes et ce que la personne voit réellement. Une bonne vue ne se contente pas de produire du HTML valide : elle protège les sorties, prévoit les collections vides, conserve les saisies incorrectes et rend le parcours évident sur ordinateur comme sur téléphone.":"That is the role of the View layer. It sits between internal data and what a person actually sees. A good view does more than produce valid HTML: it protects output, anticipates empty collections, preserves invalid input, and makes the journey obvious on desktop and phone."}</p>
    <div className="lesson-callout"><strong>{fr?"Le résultat attendu":"Expected outcome"}</strong><p>{fr?"À la fin du chapitre, l’application possédera une liste de tâches, une fiche détaillée, des formulaires create et edit, un layout commun, des partials réutilisables, des erreurs accessibles et des confirmations après redirection.":"By the end, the application will have a task list, detail page, create and edit forms, shared layout, reusable partials, accessible errors, and confirmations after redirects."}</p></div>
  </section>
}

function Summary({fr}:{fr:boolean}) {
  return <section className="lesson-rich-block course-summary">
    <p className="kicker">{fr?"En résumé":"In summary"}</p>
    <h2>{fr?"Une vue réussie rend les données sûres, lisibles et actionnables.":"A successful view makes data safe, readable, and actionable."}</h2>
    <p>{fr?"Vous savez maintenant construire une page sans mélanger présentation et métier. Le contrôleur fournit un contrat explicite; la vue échappe les valeurs, compose le layout et les partials, puis adapte le rendu aux différents états de données.":"You can now build a page without mixing presentation and business behavior. The controller supplies an explicit contract; the view escapes values, composes layout and partials, then adapts rendering to different data states."}</p>
    <ul><li>{fr?"transmettez uniquement les données nécessaires":"pass only required data"}</li><li>{fr?"échappez chaque sortie selon son contexte":"escape every output for its context"}</li><li>{fr?"prévoyez résultat, vide et erreur":"design result, empty, and error states"}</li><li>{fr?"utilisez partials et layout sans fragmenter excessivement":"use partials and layouts without excessive fragmentation"}</li><li>{fr?"rendez formulaires et erreurs accessibles":"make forms and errors accessible"}</li><li>{fr?"testez le comportement visible, pas le détail CSS":"test visible behavior, not CSS details"}</li></ul>
    <p>{fr?"Au chapitre 7, nous donnerons à ces pages leur identité visuelle avec CSS, JavaScript progressif, images et une stratégie propre pour les ressources publiques et le cache navigateur.":"In chapter 7, we will give these pages visual identity through CSS, progressive JavaScript, images, and a clean strategy for public assets and browser caching."}</p>
  </section>
}

export function ChapterSix({locale}:{locale:"en"|"fr"}) {
  const fr=locale==="fr", prefix=fr?"/fr":"";
  return <><Header locale={locale} path="/tutorial/06"/><main className="lesson-page views-lesson">
    <section className="lesson-hero shell"><div><p className="eyebrow"><span/>{fr?"Tutoriel MVC · Chapitre 06":"MVC tutorial · Chapter 06"}</p><h1>{fr?<>Créer les vues<br/><em>et les partials.</em></>:<>Create views<br/><em>and partials.</em></>}</h1><p>{fr?"Transformez les données du contrôleur en pages sûres, accessibles et faciles à maintenir.":"Turn controller data into safe, accessible, maintainable pages."}</p></div><aside><small>{fr?"OBJECTIF":"OUTCOME"}</small><strong>{fr?"L’interface complète des tâches":"Complete task interface"}</strong><span>≈ 210 min</span></aside></section>
    <section className="route-equation shell"><span>DATA</span><b>→</b><span>VIEW</span><b>→</b><span>HTML</span><b>→</b><strong>USER</strong></section>
    <div className="lesson-layout shell"><nav className="lesson-toc"><strong>{fr?"Dans ce chapitre":"In this chapter"}</strong>{lessons.map(x=><a href={`#s-${x.n}`} key={x.n}><span>{x.n}</span>{fr?x.fr:x.en}</a>)}<a href="#workshop"><span>✓</span>{fr?"Atelier":"Workshop"}</a></nav><article className="lesson-content">
      <Opening fr={fr}/>
      {lessons.map((x,i)=><section className="lesson-section route-lesson-part" id={`s-${x.n}`} key={x.n}><span className="lesson-number">{x.n}</span><h2>{fr?x.fr:x.en}</h2>{(fr?x.frText:x.enText).map((p,j)=><p className={j===0?"route-lead":undefined} key={p}>{p}</p>)}<div className="route-understand"><strong>{fr?"À retenir":"Remember"}</strong><p>{fr?x.frRule:x.enRule}</p></div>{i===1&&<CodeBlock>{controllerCode}</CodeBlock>}{i===2&&<CodeBlock>{escapedCode}</CodeBlock>}{i===3&&<CodeBlock>{listCode}</CodeBlock>}{i===6&&<CodeBlock>{formCode}</CodeBlock>}</section>)}
      <section className="lesson-exercise" id="workshop"><p className="kicker">{fr?"Atelier guidé":"Guided workshop"}</p><h2>{fr?"Construisez toutes les vues de Task.":"Build every Task view."}</h2><ol>{(fr?["Créez le layout avec métadonnées, header, main et footer.","Construisez index avec liste et état vide.","Extrayez une carte de tâche réutilisable.","Créez show, create et edit.","Ajoutez CSRF, anciennes valeurs et erreurs accessibles.","Affichez les messages flash après redirection.","Testez une charge XSS, l’état vide et les liens nommés."]:["Create the layout with metadata, header, main, and footer.","Build index with list and empty state.","Extract a reusable task card.","Create show, create, and edit.","Add CSRF, old values, and accessible errors.","Display flash messages after redirects.","Test an XSS payload, empty state, and named links."]).map(x=><li key={x}>{x}</li>)}</ol></section>
      <section className="lesson-rich-block lesson-correction"><p className="kicker">{fr?"Correction raisonnée":"Reasoned solution"}</p><h2>{fr?"Relisez la page comme un utilisateur et comme un attaquant.":"Read the page as a user and as an attacker."}</h2><p>{fr?"L’utilisateur doit comprendre la hiérarchie, trouver l’action suivante et corriger une erreur sans perdre sa saisie. L’attaquant, lui, ne doit jamais transformer un titre de tâche en code actif. Vérifiez ces deux perspectives avant de considérer la vue terminée.":"Users must understand hierarchy, find the next action, and correct errors without losing input. Attackers must never turn a task title into active code. Verify both perspectives before considering the view complete."}</p><details><summary>{fr?"Faut-il créer un partial pour chaque élément ?":"Should every element become a partial?"}</summary><p>{fr?"Non. Extrayez les unités réutilisées ou conceptuellement autonomes. Gardez ensemble le HTML qui se comprend mieux ensemble.":"No. Extract reused or conceptually independent units. Keep together HTML that is easier to understand together."}</p></details></section>
      <Summary fr={fr}/>
    </article></div>
    <section className="lesson-navigation shell"><Link href={`${prefix}/tutorial/05`}>← {fr?"Chapitre 05":"Chapter 05"}</Link><span>{fr?"Chapitre 07 · À venir":"Chapter 07 · Coming soon"} 🔒</span></section>
  </main><Footer locale={locale}/></>;
}
