import Link from "next/link";
import { Footer, Header } from "../components";

const chapters = [
  { n:"01", en:"Install AML and create a project", fr:"Installer AML et créer un projet", enTopics:["AML versus PHPAML","Install on Windows, macOS, and Linux","Choose the CLI language","Run aml doctor","Create and install a project","Start live reload","Troubleshoot installation"], frTopics:["AML et PHPAML","Installer sur Windows, macOS et Linux","Choisir la langue de la CLI","Exécuter aml doctor","Créer et installer un projet","Lancer l’actualisation automatique","Résoudre les problèmes d’installation"] },
  { n:"02", en:"Understand the PHPAML structure", fr:"Comprendre la structure PHPAML", enTopics:["MVC overview","Controllers and models","Views and partials","Configuration files","Database and migrations","Public assets","The private aml_env engine"], frTopics:["Vue générale de MVC","Contrôleurs et modèles","Vues et partials","Fichiers de configuration","Base et migrations","Fichiers publics","Le moteur privé aml_env"] },
  { n:"03", en:"Follow an HTTP request", fr:"Suivre une requête HTTP", enTopics:["HTTP methods","Paths and parameters","Request and Response","Middleware pipeline","Router selection","Controller execution","The complete lifecycle"], frTopics:["Méthodes HTTP","Chemins et paramètres","Request et Response","Pipeline des middlewares","Sélection par le routeur","Exécution du contrôleur","Cycle de vie complet"] },
  { n:"04", en:"Define and organize routes", fr:"Définir et organiser les routes", enTopics:["GET and POST routes","Controller handlers","Dynamic parameters","Named routes","Route groups","Route middleware","404 and 405 responses"], frTopics:["Routes GET et POST","Actions de contrôleur","Paramètres dynamiques","Routes nommées","Groupes de routes","Middleware par route","Réponses 404 et 405"] },
  { n:"05", en:"Build controllers", fr:"Construire les contrôleurs", enTopics:["TaskController","CRUD actions","Receive a Request","Render a view","Redirect after forms","Return JSON","Dependency injection"], frTopics:["TaskController","Actions du CRUD","Recevoir une Request","Rendre une vue","Rediriger après un formulaire","Retourner du JSON","Injection de dépendances"] },
  { n:"06", en:"Create views and partials", fr:"Créer les vues et partials", enTopics:["Pass view data","Escape output","Conditions and loops","Header and footer partials","Create and edit forms","Validation errors","Flash messages"], frTopics:["Transmettre les données","Échapper les sorties","Conditions et boucles","Partials header et footer","Formulaires de création et modification","Erreurs de validation","Messages flash"] },
  { n:"07", en:"Add CSS, JavaScript, and images", fr:"Ajouter CSS, JavaScript et images", enTopics:["Public asset URLs","Responsive CSS","Form styling","Progressive JavaScript","Delete confirmation","Images and favicon","Browser cache diagnostics"], frTopics:["URL des fichiers publics","CSS responsive","Style des formulaires","JavaScript progressif","Confirmation de suppression","Images et favicon","Diagnostic du cache navigateur"] },
  { n:"08", en:"Configure SQLite and migrations", fr:"Configurer SQLite et les migrations", enTopics:["Environment variables","Database CLI configuration","PDO connection","Create the tasks table","Run migrations","Rollback safely","Development versus production"], frTopics:["Variables d’environnement","Configuration en CLI","Connexion PDO","Créer la table tasks","Exécuter les migrations","Annuler sans risque","Développement et production"] },
  { n:"09", en:"Create the model", fr:"Créer le modèle", enTopics:["Task model","Read and find records","Insert a task","Update its state","Delete safely","QueryBuilder","Transactions"], frTopics:["Modèle Task","Lire et rechercher","Insérer une tâche","Modifier son état","Supprimer sans risque","QueryBuilder","Transactions"] },
  { n:"10", en:"Assemble the complete MVC app", fr:"Assembler l’application MVC", enTopics:["Connect every MVC layer","List tasks","Create and edit","Complete and reopen","Delete a task","Handle missing records","Add a due-date challenge"], frTopics:["Relier toutes les couches MVC","Lister les tâches","Créer et modifier","Terminer et rouvrir","Supprimer une tâche","Gérer les ressources absentes","Défi avec date limite"] },
  { n:"11", en:"Validate, secure, and debug", fr:"Valider, sécuriser et déboguer", enTopics:["Input validation","Output escaping","CSRF protection","Secure sessions","Security headers","404 and 500 pages","APP_DEBUG and logs"], frTopics:["Validation des entrées","Échappement des sorties","Protection CSRF","Sessions sécurisées","En-têtes de sécurité","Pages 404 et 500","APP_DEBUG et journaux"] },
  { n:"12", en:"Test, build, and deploy", fr:"Tester, construire et déployer", enTopics:["Route and controller tests","Model test database","Run aml test","Production diagnostics","SEO and sitemap","Run aml build","Deploy over SSH or SFTP"], frTopics:["Tests des routes et contrôleurs","Base temporaire de test","Exécuter aml test","Diagnostic de production","SEO et sitemap","Exécuter aml build","Déployer avec SSH ou SFTP"] },
] as const;

export function TutorialPage({ locale }: { locale:"en"|"fr" }) {
  const fr = locale === "fr"; const prefix = fr ? "/fr" : "";
  return <><Header locale={locale} path="/tutorial" /><main className="tutorial-page">
    <section className="tutorial-hero shell">
      <div className="tutorial-hero-copy"><p className="eyebrow"><span /> {fr?"Tutoriel officiel PHPAML":"Official PHPAML tutorial"}</p><h1>{fr?<>Maîtrisez MVC.<br/><em>Construisez pour de vrai.</em></>:<>Master MVC.<br/><em>Build something real.</em></>}</h1><p>{fr?"Un parcours riche et progressif pour créer une application de tâches complète avec routes, contrôleurs, modèles, vues, SQLite, sécurité et tests.":"A rich, progressive path to build a complete task application with routes, controllers, models, views, SQLite, security, and tests."}</p>
        <div className="tutorial-actions"><a className="button primary" href="#chapters">{fr?"Voir les chapitres":"Explore chapters"} <span>↓</span></a><Link className="button ghost" href={`${prefix}/docs`}>{fr?"Référence technique":"Technical reference"} <span>→</span></Link></div>
      </div>
      <div className="tutorial-cycle" aria-label={fr?"Cycle MVC":"MVC lifecycle"}><small>{fr?"CYCLE D’UNE REQUÊTE":"REQUEST LIFECYCLE"}</small><div><span>Route</span><b>→</b><span>Controller</span><b>→</b><span>Model</span><b>→</b><span>View</span></div><p>{fr?"Une architecture explicite où chaque élément possède une responsabilité claire.":"An explicit architecture where every part has one clear responsibility."}</p></div>
    </section>
    <section className="tutorial-stats"><div className="shell"><div><strong>12</strong><span>{fr?"chapitres":"chapters"}</span></div><div><strong>80+</strong><span>{fr?"notions":"concepts"}</span></div><div><strong>1</strong><span>{fr?"application complète":"complete application"}</span></div><div><strong>2</strong><span>{fr?"langues":"languages"}</span></div></div></section>
    <section className="tutorial-prereqs shell"><div><span className="section-number">/ 00</span><p className="kicker">{fr?"Avant de commencer":"Before you start"}</p><h2>{fr?"Quelques bases. Aucun environnement à bricoler.":"A few basics. No environment to assemble."}</h2></div><ul><li>{fr?"Bases de PHP et des classes":"PHP and class fundamentals"}</li><li>{fr?"HTML, CSS et formulaires":"HTML, CSS, and forms"}</li><li>{fr?"Commandes simples du terminal":"Basic terminal commands"}</li><li>{fr?"Notions GET, POST et base de données":"GET, POST, and database concepts"}</li></ul><p>{fr?"AML fournit PHP, Composer, SQLite et le serveur local.":"AML provides PHP, Composer, SQLite, and the local server."}</p></section>
    <section className="tutorial-roadmap shell" id="chapters"><div className="tutorial-heading"><span className="section-number">/ 01—12</span><div><p className="kicker">{fr?"Table des matières":"Table of contents"}</p><h2>{fr?"Du premier terminal à la production.":"From first terminal to production."}</h2></div><p>{fr?"Chaque chapitre contient des explications, du code progressif, des erreurs fréquentes, un exercice et une liste de vérification.":"Every chapter includes explanations, progressive code, common mistakes, an exercise, and a checklist."}</p></div>
      <div className="chapter-list">{chapters.map((chapter)=><article className="chapter-card chapter-card-locked" key={chapter.n}><div className="chapter-index"><span>{chapter.n}</span></div><div className="chapter-body"><small>{fr?`CHAPITRE ${chapter.n}`:`CHAPTER ${chapter.n}`}</small><h3>{fr?chapter.fr:chapter.en}</h3><ol>{(fr?chapter.frTopics:chapter.enTopics).map((topic,i)=><li key={topic}><span>{chapter.n}.{i+1}</span>{topic}</li>)}</ol></div><div className="chapter-status chapter-status-locked"><span aria-hidden="true">🔒</span><strong>{fr?"À venir":"Coming soon"}</strong></div></article>)}</div>
    </section>
    <section className="tutorial-project"><div className="shell"><div><p className="kicker">{fr?"Projet fil rouge":"Course project"}</p><h2>{fr?<>Construisez une vraie<br/><em>application de tâches.</em></>:<>Build a real<br/><em>task application.</em></>}</h2><p>{fr?"CRUD complet, SQLite, validation, CSRF, sessions, tests, SEO et déploiement. Chaque chapitre ajoute une partie fonctionnelle au même projet.":"Complete CRUD, SQLite, validation, CSRF, sessions, tests, SEO, and deployment. Every chapter adds a working piece to the same project."}</p></div><div className="project-checklist">{[fr?"Créer et modifier":"Create and edit",fr?"Terminer et filtrer":"Complete and filter",fr?"Valider et sécuriser":"Validate and secure",fr?"Tester et déployer":"Test and deploy"].map((item,i)=><div key={item}><span>0{i+1}</span><strong>{item}</strong><b>✓</b></div>)}</div></div></section>
    <section className="tutorial-cta shell"><div><p className="kicker">{fr?"Bientôt disponible":"Coming next"}</p><h2>{fr?"Le cours complet sera publié chapitre par chapitre.":"The complete course will be released chapter by chapter."}</h2></div><Link className="button primary" href={`${prefix}/docs`}>{fr?"Préparer les bases":"Review the basics"} <span>→</span></Link></section>
  </main><Footer locale={locale}/></>;
}

export default function Tutorial(){ return <TutorialPage locale="en"/>; }
